version: "3.8"
services:  
  postgresql:
    image: postgres:12.4
    ports:
      - 5432:5432
    environment:
      - PGDATA=/postgresql
      - POSTGRES_PASSWORD=prempicksAPIdb
    volumes:
      - ./tmp/data/postgresql:/postgresql
  redis:
    image: redis
    ports:
      - 6379:6379