:verbose: false
:concurrency: 4

:timeout: 8
:queues:
  - [default, 4]
  - [mailers, 2]
:schedule:
  firebase_cert_req:
    cron: '0 */30 * * * *'
    class: FirebaseCertReqJob
    queue: default
  set_matchday:
    cron: '0 */10 * * * *'
    class: SetMatchdayJob
    queue: default
  update_locktimes:
    cron: '0 0 * * * *'
    class: UpdateLocktimesJob
    queue: default
  queue_reminders:
    cron: '0 0 */6 * * *'
    class: QueueRemindersJob
    queue: default